#!/usr/bin/env bash
# =============================================================================
# HomeLab Stack — DNS Port Conflict Resolution Script
# Detects and resolves systemd-resolved port 53 conflicts with AdGuard
# Usage: ./scripts/fix-dns-port.sh [--check|--apply|--restore]
#   --check   : Detect conflicts without making changes
#   --apply   : Apply fix (stop systemd-resolved, update resolv.conf)
#   --restore : Restore systemd-resolved to original state
# =============================================================================
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT_DIR=$(dirname "$SCRIPT_DIR")

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
log_info()  { echo -e "${GREEN}[INFO]${RESET} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${RESET} $*"; }
log_error() { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
log_step()  { echo; echo -e "${BOLD}${CYAN}==> $*${RESET}"; }

ACTION="${1:-}"
RESOLV_CONF_BACKUP="/tmp/resolv.conf.backup.$(date +%s)"
RESOLV_CONF="/etc/resolv.conf"

# Check if running as root
check_root() {
  if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
  fi
}

# Check if systemd-resolved is using port 53
check_conflict() {
  log_step "Checking DNS port conflicts..."

  # Check if anything is listening on port 53
  local tcp53 udp53
  tcp53=$(ss -tlnp 2>/dev/null | grep ':53 ' | grep 'tcp' || true)
  udp53=$(ss -ulnp 2>/dev/null | grep ':53 ' | grep 'udp' || true)

  # Check systemd-resolved status
  local resolved_active resolved_using_53
  if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
    resolved_active="yes"
    # Check if resolved is actually binding to 53
    if ss -tlnp | grep -q ':53 ' && systemd-resolve --status 2>/dev/null | grep -q 'DNS Servers.*:53'; then
      resolved_using_53="yes"
    else
      resolved_using_53="no"
    fi
  else
    resolved_active="no"
    resolved_using_53="no"
  fi

  echo ""
  echo "  systemd-resolved active : $resolved_active"
  echo "  systemd-resolved on :53 : $resolved_using_53"
  echo ""
  echo "  TCP/53 listeners:"
  if [[ -n "$tcp53" ]]; then
    echo "$tcp53" | sed 's/^/    /'
  else
    echo "    (none)"
  fi
  echo ""
  echo "  UDP/53 listeners:"
  if [[ -n "$udp53" ]]; then
    echo "$udp53" | sed 's/^/    /'
  else
    echo "    (none)"
  fi
  echo ""

  # Determine if conflict exists
  if [[ -n "$tcp53" ]] || [[ -n "$udp53" ]]; then
    log_warn "Port 53 conflict detected!"
    echo "  AdGuard will fail to bind to port 53."
    echo "  Run with --apply to resolve, or --check to see details."
    return 1
  else
    log_info "No port 53 conflicts detected."
    return 0
  fi
}

# Apply the fix
apply_fix() {
  check_root
  log_step "Applying DNS port conflict fix..."

  # Check if systemd-resolved is active
  if ! systemctl is-active --quiet systemd-resolved 2>/dev/null; then
    log_info "systemd-resolved is not active — nothing to do."
    exit 0
  fi

  # Backup resolv.conf
  if [[ ! -f "$RESOLV_CONF_BACKUP" ]] || [[ ! -f "/tmp/resolv.conf.backup.first" ]]; then
    local backup_file="/tmp/resolv.conf.backup.first"
    cp "$RESOLV_CONF" "$backup_file"
    log_info "Backed up $RESOLV_CONF to $backup_file"
  fi

  # Stop systemd-resolved
  log_info "Stopping systemd-resolved..."
  systemctl stop systemd-resolved 2>/dev/null || true

  # Disable systemd-resolved to prevent it from starting again on reboot
  systemctl mask systemd-resolved 2>/dev/null || true

  # Update resolv.conf to use external DNS
  # Use Cloudflare and Google DNS as defaults
  log_info "Updating $RESOLV_CONF with public DNS servers..."
  cat > "$RESOLV_CONF" << 'RESOLV_EOF'
# Generated by homelab-stack fix-dns-port.sh
# Previous config backed up to /tmp/resolv.conf.backup.first
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 8.8.8.8
nameserver 8.8.4.4
RESOLV_EOF

  log_info "Fix applied successfully!"
  echo ""
  echo "  systemd-resolved has been stopped and masked."
  echo "  /etc/resolv.conf now points to public DNS servers."
  echo "  AdGuard should now be able to bind to port 53."
  echo ""
  echo "  To restore later, run: sudo $0 --restore"
}

# Restore systemd-resolved
restore() {
  check_root
  log_step "Restoring systemd-resolved..."

  # Find the most recent backup
  local backup_file
  backup_file=$(ls -t /tmp/resolv.conf.backup.first 2>/dev/null | head -1)

  if [[ -z "$backup_file" ]] || [[ ! -f "$backup_file" ]]; then
    log_warn "No backup file found. Cannot restore."
    echo "  systemd-resolved will use its default configuration."
  else
    log_info "Restoring $RESOLV_CONF from $backup_file"
    cp "$backup_file" "$RESOLV_CONF"
  fi

  # Unmask and restart systemd-resolved
  log_info "Restarting systemd-resolved..."
  systemctl unmask systemd-resolved 2>/dev/null || true
  systemctl start systemd-resolved 2>/dev/null || true

  # Restore backup file removal
  rm -f /tmp/resolv.conf.backup.first 2>/dev/null || true

  log_info "Restoration complete!"
}

# Main
case "${ACTION}" in
  --check)
    check_conflict
    ;;
  --apply)
    check_conflict || true
    echo ""
    read -p "Apply fix? This will stop systemd-resolved. Continue? (y/N) " -r
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      apply_fix
    else
      log_info "Aborted."
      exit 0
    fi
    ;;
  --restore)
    restore
    ;;
  *)
    echo "Usage: $0 [--check|--apply|--restore]"
    echo ""
    echo "  --check   Detect DNS port conflicts without making changes"
    echo "  --apply   Stop systemd-resolved and fix /etc/resolv.conf"
    echo "  --restore Restore systemd-resolved to original state"
    echo ""
    echo "NOTE: systemd-resolved often conflicts with AdGuard on port 53."
    echo "      Use --check first to diagnose, --apply to fix."
    exit 1
    ;;
esac
